name: Deploy to Azure App Service

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Push to Azure Docker Registry
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: mycontainer.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      - run: |
          docker build . -t mycontainer.azurecr.io/myapp:${{ github.sha }}
          docker push mycontainer.azurecr.io/myapp:${{ github.sha }}